spring:
  application:
    name: service-01

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 0 # random port

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# /actuator/refresh 엔드포인트 활성화
management:
  endpoints:
    web:
      exposure:
        include: refresh

setting:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      topic: example
      group-id: example-group
      enable-auto-commit: false
      auto-offset-reset: earliest


